language: node_js
node_js:
  - "node"
script: ./node_modules/.bin/mermaid -o site hacks.mmd
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: site
  on:
    branch: master
